name: Publish docs

on:
  push:
    tags:
      - 'v*.*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - uses: actions/cache@v2
      id: nuget
      with:
        path: |
          ~/.nuget/packages
          src/StormworksLuaDocsGen/**/obj/**
        key: nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: nuget

    - name: Restore with dotnet
      if: steps.nuget.outputs.cache-hit != 'true'
      run: dotnet restore ./src/StormworksLuaDocsGen
      
    - name: Build
      run: dotnet build ./src/StormworksLuaDocsGen/StormworksLuaDocsGen.csproj -o ./Build --no-restore
      
    - name: Generate mission docs
      run: dotnet ./Build/StormworksLuaDocsGen.dll --output docs-missions.lua --docs-url https://docs.google.com/spreadsheets/d/1joiH8eu6LOE76lL0ijNoUe-3VsVDfMkAnfHY-trCt9Y
      
    - name: Generate vehicle docs
      run: dotnet ./Build/StormworksLuaDocsGen.dll --output docs-vehicles.lua --docs-url https://docs.google.com/spreadsheets/d/1tCvYSzxnr5lWduKlePKg4FerpeKHbKTmwmAxlnjZ_Go

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          docs-missions.lua
          docs-vehicles.lua
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
